### ISSUE TITLE
Incorrect formatting of HTML in some cases

### ISSUE THREAD

**Issue by null-dev** [UnwrittenFun/prettier-plugin-svelte#14]
HTML like this:
```html
<div>
  <MyIcon />
  Current score: [{score}]
</div>
```

gets formatted like this:
```html
<div>
  <MyIcon />
  Current score: [
  {score}
  ]
</div>
```

At first glance, this looks fine, but the issue is that these two HTML segments are actually displayed differently in the browser. Assume the score is `10`.

- The first segment is displayed like so: `Current score: [10]`
- The second segment is displayed like so: `Current score: [ 10 ]`

Notice the extra spaces inside the brackets.

**Comment by jarrodldavis** [comment]
@UnwrittenFun I think this is because all of the children of an element are part of the parent's `group`, so the `hardline`s from nested elements cause all of the `line`s and `softline`s in that `group` to break as well. I think the best way to fix that is to make sub `group`s of sibling inline (`MustacheTag` and `Text`) nodes so that they don't break prematurely.
